### ISSUE TITLE
Issue edit view button submit not submiting V1.2 8.6 umbraco

### ISSUE THREAD

**Issue by bardaji** [skttl/umbraco-doc-type-grid-editor#187] opened 2020-04-16 17:15 UTC
Not submiting when editing in view.
![image](https://user-images.githubusercontent.com/19190905/79486153-95422f80-8016-11ea-905a-eebb5b326491.png)

**Comment by bardaji** [comment] 2020-04-16 17:16
Let me know if you need more info.

Im just trying to insert a layout grid in doctype and render in edit view ,

**Comment by bardaji** [comment] 2020-04-17 11:09
function submit() {
                 
                if ($scope.model.submit) {
                    
                    $scope.model.node.name = "Dtge Temp: " + $scope.model.node.key;
                    $scope.model.node.variants[0].name = $scope.model.node.name;
                    $scope.model.node.variants[0].save = true;
                    
                    // save the content as a blueprint, to trigger validation
                    var args = {
                        saveMethod: contentResource.saveBlueprint,
                        scope: $scope,
                        content: $scope.model.node,
                        create: true,
                        action: "save",
                        showNotifications: true,
                        softRedirect: true
                    };
SOLVED with this.
               `     $scope.model.close();`

**Comment by skttl** [comment] 2020-04-17 12:47
Where did you put the close call? Are you sure it doesn't have other implications?

**Comment by bardaji** [comment] 2020-04-18 11:02
I have tested the functions and it seems that everything works well, I understand that it is the submit function that goes through all the forms that the editor has already done.

The main js doctypegrideditor.controllers.js and function 

`  function submit() {
                 
                if ($scope.model.submit) {
                    
                    $scope.model.node.name = "Dtge Temp: " + $scope.model.node.key;
                    $scope.model.node.variants[0].name = $scope.model.node.name;
                    $scope.model.node.variants[0].save = true;
                    
                    // save the content as a blueprint, to trigger validation
                    var args = {
                        saveMethod: contentResource.saveBlueprint,
                        scope: $scope,
                        content: $scope.model.node,
                        create: true,
                        action: "save",
                        showNotifications: true,
                        softRedirect: true
                    };
                    $scope.model.close();
                    contentEditingHelper.contentEditorPerformSave(args).then(function (data) {
                        $scope.model.submit($scope.model);
                    },
                        function (err) {
                            alert(err);
                        });
                } else {
                    alert('no submit');  
                }
            }`


I just put ` $scope.model.close();`

                    `<umb-button` type="button"
                                button-style="action"
                                label-key="general_submit"
                                shortcut="ctrl+s"
                                ng-if="dialogMode == 'edit'"
                                action="vm.submit()">
                    </umb-button>`

**Comment by bardaji** [comment] 2020-04-20 10:42
Finally I have not managed to get version 1.2 uploaded to production, it may be due to having the custom url or some plugin that is interfering with your addon- Angular js error, if you need more info let me know, in the meantime I will wait for another version to use it.

**Comment by SvenGoormans** [comment] 2020-04-21 06:53
Hey Bardaji, I have exactly the same issue as you. But adding $scope.model.close tot the function submit() doesn't really help me out :/ Any other ideas ? 
Thank you !

**Comment by skttl** [comment] 2020-04-21 08:58
I can't reproduce this on a clean install of Umbraco 8.6 with a clean install of DTGE 1.2.

Can you provide steps to reproduce?

**Comment by saadan** [comment] 2020-05-04 18:58
Maybe there is something similar with the Member Group Picker. 
When pressing the submit button the window just close and nothing is inserted.

**Comment by skttl** [comment] 2020-05-27 11:51
I think this has been fixed in 1.2.1 or 1.2.2. I still can't reproduce, so I am closing this.

**Closed by skttl** 2020-05-27 11:51 UTC
Labels: details-needed
