### ISSUE TITLE
Doc Type Grid Editor 1.2.3 - Unsaved Changes dialog fires when hitting submit on grid editors

### ISSUE THREAD

**Issue by loriRyanp** [skttl/umbraco-doc-type-grid-editor#205] opened 2020-06-09 07:26 UTC
I've just upgraded to the latest version v1.2.3

When I create a new page, choose a grid layout and add a custom grid editor to it on the submit it seems to be firing the

You have unsaved changes Are you sure you want to navigate away from this page? - you have unsaved changes

I click stay and the editor renders fine.

These were working in the previous version and not firing this event.

When the page is already saved this doesnt happen - any ideas how I can prevent this?

Unsure if related Ive the latest version of Matryoshka 0.4.0 installed.

**Comment by mcl-sz** [comment] 2020-06-09 08:45
I'm experiencing the same issue.

**Comment by loriRyanp** [comment] 2020-06-13 16:28
Hi dont think the problem is with doctypegrid editor I think its the combination of doctypegrid editor and Matryoshka 0.4.0. Just started a project to try debug the situation. No Matryoshka just doctypegrid editor no issue

**Comment by mcl-sz** [comment] 2020-06-15 09:01
I've did a clean install of Umbraco with starterkit and added only DoctypeGrid. When i create a new page i get the unsaved changes warning. So i guess Matryoshka  is not interfering for this issue.

**Comment by mcl-sz** [comment] 2020-06-15 11:47
When line 283 is commented out, 

`contentEditingHelper.contentEditorPerformSave(args).then(function (data) {`

the dialog doesn't appear. So it looks like contentEditingHelper.contentEditorPerformSave has something to do with it. Maybe this is changed in Umbraco 8.6 and higher.

**Comment by skttl** [comment] 2020-06-15 12:08
@mcl-sz what version are you on?

**Comment by mcl-sz** [comment] 2020-06-15 12:33
@skttl on version 1.2.3 in combination with Umbraco 8.6.2

**Comment by mcl-sz** [comment] 2020-06-15 13:08
I've added the infiniteMode: true option. Now the warning is gone and it works for simple doctypes but not when Nested Content is used in a doctype:

```
                    // save the content as a blueprint, to trigger validation
                    var args = {
                        saveMethod: contentResource.saveBlueprint,
                        scope: $scope,
                        content: $scope.model.node,
                        create: true,
                        action: "save",
                        showNotifications: false,
                        softRedirect: true,
                        **infiniteMode: true**
                    };

                    contentEditingHelper.contentEditorPerformSave(args).then(function (data) {
                        $scope.model.submit($scope.model);
                        **if (data.id) {
                            $scope.model.node.id = data.id;
                            cleanup();
                        }**

                    },
                    function (err) {
                        // cleanup the blueprint immediately
                        cleanup();
                    });
```

**Comment by skttl** [comment] 2020-06-15 13:56
Thanks for updating @mcl-sz

**Comment by mcl-sz** [comment] 2020-06-15 14:49
It looks like there is a problem with validation of a blueprint that contains nested content. When i create a blueprint manualy via the Umbraco backoffice that contains nested content, it is saved even when the nested content contains errors.

**Comment by mcl-sz** [comment] 2020-06-15 15:19
The wierd thing is that the popup is only shown when you create a new content node. I compared the args parameter from a already saved document and a new unsaved document and except for the keys they are identical.

**Comment by skttl** [comment] 2020-08-26 18:27
Just tried 8.6.4, with DTGE 1.2.3 and Matryoshka 0.4.0.

Created a doc type with a Nested Content property.

Added the DTGE block, and filled the NC property. Clicked Submit. Everything went as expected.

How are you getting this?

**Comment by loriRyanp** [comment] 2020-08-26 21:18
For me if I do the following I get the issue.
Just create a page, choose a grid layout and add a custom grid editor.
![GridProblem](https://user-images.githubusercontent.com/59826692/91357986-fe6a5880-e7e9-11ea-9f53-4a9008560231.gif)

**Comment by skttl** [comment] 2020-08-27 06:30
Thanks, and you are on 1.2.3? Did you update from previous versions?

What is that H-tag selector?

**Comment by loriRyanp** [comment] 2020-08-27 08:20
Hi 

Yes I am on 1.2.3. 

Its a custom property type that Ive made. But it happens regardless if I use an grid editor that has only OTB umbraco property types or one that has custom property types. I can send example if needed?

**Comment by inetzo** [comment] 2020-09-08 09:39
Hi @skttl ,

It's not difficult to reproduce it with the default Umbraco Starterkit.

Create a documenttype containing an Nested Content property and assign the "Feature" elementtype to it and make the property required. I've added an export from the Doctype I'm using (UDT file):

<DocumentType>
	<Info>
		<Name>Nested Content</Name>
		<Alias>nestedContent</Alias>
		<Icon>icon-document</Icon>
		<Thumbnail>folder.png</Thumbnail>
		<Description/>
		<AllowAtRoot>False</AllowAtRoot>
		<IsListView>False</IsListView>
		<IsElement>True</IsElement>
		<Variations>Nothing</Variations>
		<Compositions/>
		<AllowedTemplates>
			<Template>NestedContent</Template>
		</AllowedTemplates>
		<DefaultTemplate>NestedContent</DefaultTemplate>
	</Info>
	<Structure/>
	<GenericProperties>
		<GenericProperty>
			<Name>Nested</Name>
			<Alias>nested</Alias>
			<Type>Umbraco.NestedContent</Type>
			<Definition>fa322cb2-2670-4bb2-8d1f-850d855052b2</Definition>
			<Tab>Content</Tab>
			<SortOrder>0</SortOrder>
			<Mandatory>True</Mandatory>
			<Variations>Nothing</Variations>
		</GenericProperty>
	</GenericProperties>
	<Tabs>
		<Tab>
			<Id>30</Id>
			<Caption>Content</Caption>
			<SortOrder>0</SortOrder>
		</Tab>
	</Tabs>
</DocumentType>

Now create an a new page under "About us" and add this element to the grid  and click the "Submit" button in the DTGE window.
The unsaved changes dialog appears.

The dialog references to the saved blueprint.

**Comment by skttl** [comment] 2020-09-08 09:56
Thanks - I'll check up on this. Feel free to see if you can spot the problem too :)

**Comment by inetzo** [comment] 2020-09-08 16:44
I think i have found the problem but i do not have an idea how to workaround this:

In the redirectToCreatedContent method in the umbraco.services.contentEditingHelper there is an if-statement to check if  $routeParams.create  has a value. Because it's a new page, this value is "true" when a new page is created (it's in the browsers-url)
Existing pages do not have this parameter in the url so that why it only happens on new pages. 

I made a dirty fix for this by capturing the $routeParams.create value before saving and resetting it afterwards.
#0c54b21446c22f480a03745046267f773e42bbbd

(This is the firstime a made a pull request and submitted changes so maybye it's not the way it usually has to be is done)

**Comment by inetzo** [comment] 2020-09-08 17:08
I think i have found the problem and made a small workaround:

In the redirectToCreatedContent method in the umbraco.services.contentEditingHelper there is an if-statement to check if  $routeParams.create  has a value. Because it's a new page, this value is "true" when a new page is created (it's in the browsers-url)
Existing pages do not have this parameter in the url so that why it only happens on new pages. 

I made a dirty fix for this by capturing the $routeParams.create value before saving and resetting it afterwards.

This is the firstime a made a pull request and submitted changes so maybye it's not the way it usually has to be is done. Sorry!

**Comment by skttl** [comment] 2020-09-08 18:54
Thanks @inetzo works great!

**Comment by skttl** [comment] 2020-09-08 19:04
Also added a spinner in 2fc81024ac2fdab54d703d2ae4163edb9bda7c81 (I had a sloppy connection to the database, so it took some time for the blueprint to save :))

![a8Q4HTUW5h](https://user-images.githubusercontent.com/3726467/92517376-d8e04480-f216-11ea-93df-a7eb1f5dbbea.gif)

**Closed by skttl** 2020-09-08 19:04 UTC
Labels: details-needed

**Comment by loriRyanp** [comment] 2020-09-17 20:20
works great thanks so much
