### ISSUE TITLE
Umbraco 8.2 compatibility

### ISSUE THREAD

**Issue by stefanoberetta** [skttl/umbraco-doc-type-grid-editor#159] opened 2019-10-16 07:47 UTC
Hi! 

I've just update my website to U8.2
I think new functionalities of the RTE in v8.2 breaks the package giving this error (when a RTE is used)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Web.PropertyEditors.RichTextPropertyEditor.RichTextPropertyValueEditor.FromEditor(ContentPropertyData editorValue, Object currentValue) in d:\a\1\s\src\Umbraco.Web\PropertyEditors\RichTextPropertyEditor.cs:line 117
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.ConvertValue(String id, String contentTypeAlias, String dataJson)
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.<>c__DisplayClass0_0.<ConvertValueToContent>b__0()
   at Umbraco.Core.Cache.AppCacheExtensions.<>c__DisplayClass5_0`1.<GetCacheItem>b__0() in d:\a\1\s\src\Umbraco.Core\Cache\AppCacheExtensions.cs:line 62
   at Umbraco.Core.Cache.FastDictionaryAppCacheBase.<>c__DisplayClass21_0.<GetSafeLazy>b__0() in d:\a\1\s\src\Umbraco.Core\Cache\FastDictionaryAppCacheBase.cs:line 285
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Core.Cache.HttpRequestAppCache.Get(String key, Func`1 factory) in d:\a\1\s\src\Umbraco.Core\Cache\HttpRequestAppCache.cs:line 81
   at Umbraco.Core.Cache.AppCacheExtensions.GetCacheItem[T](IAppCache provider, String cacheKey, Func`1 getCacheItem) in d:\a\1\s\src\Umbraco.Core\Cache\AppCacheExtensions.cs:line 62
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.ConvertValueToContent(String id, String contentTypeAlias, String dataJson)
   at ASP._Page_app_plugins_doctypegrideditor_render_DocTypeGridEditor_cshtml.Execute() in ..\Webproject\app_plugins\doctypegrideditor\render\DocTypeGridEditor.cshtml:line 26
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at Umbraco.Web.Mvc.ProfilingView.Render(ViewContext viewContext, TextWriter writer) in d:\a\1\s\src\Umbraco.Web\Mvc\ProfilingView.cs:line 25
   at System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model)
   at ASP._Page_Views_Partials_grid_editors_Base_cshtml.Execute() in ..\Webproject\Views\Partials\grid\editors\Base.cshtml:line 20
```

**Comment by DynamicDave** [comment] 2019-10-16 19:08
Me too... same problem here. Even when i'm using a textarea in stead of a rte.

**Comment by cpevans** [comment] 2019-10-16 21:18
I'm also experiencing this exact same issue.

**Comment by thomassen88** [comment] 2019-10-17 11:35
Same problem here. RTE seems to crash DTGE.

**Comment by Jeavon** [comment] 2019-10-17 16:35
The exception is coming from https://github.com/umbraco/Umbraco-CMS/commit/03a4affbde4948afbcccc7fbea6a2327c97f8c40#diff-99ef99ed499fd7e582df2066ec073f41R89 As this is coming from the front end where there is no Umbraco user so CurrentUser is null apart from when in preview mode
Attached is a modified 8.2 Umbraco.Web.dll with a fix
[Umbraco.Web.dll.zip](https://github.com/skttl/umbraco-doc-type-grid-editor/files/3740347/Umbraco.Web.dll.zip)

**Comment by skttl** [comment] 2019-10-20 14:35
Good find @Jeavon 

I'm curious if something can be done in DTGE to make it work with 8.2. Do you know if there is something we can do, or do we just have to wait for 8.2.1 (assuming your PR gets merged)

**Comment by milandt** [comment] 2019-10-20 14:45
The issue is already on Umbraco bugfix list for 8.2.1 to be released soon, so it will be fixed. I used the build with the fix, and didn't see any other problems continuing using the same version of DTGE

**Comment by cpevans** [comment] 2019-10-21 02:51
> The issue is already on Umbraco bugfix list for 8.2.1 to be released soon, so it will be fixed. I used the build with the fix, and didn't see any other problems continuing using the same version of DTGE

I can't see that here: https://our.umbraco.com/download/releases/821   - how can you tell it will be part of 8.2.1?

Is there a way to get the PR by @Jeavon noticed by the HQ? It doesn't seem to have any versions assigned to it.

**Comment by milandt** [comment] 2019-10-21 06:31
No you are right, I mistook it for another issue. It's not there.

**Comment by milandt** [comment] 2019-10-21 06:32
Can someone on Twitter perhaps notify Umbraco about it? :)

**Comment by Jeavon** [comment] 2019-10-21 09:13
Don't worry, it will be included in v8.2.1

**Comment by Jeavon** [comment] 2019-10-21 09:14
> Good find @Jeavon
> 
> I'm curious if something can be done in DTGE to make it work with 8.2. Do you know if there is something we can do, or do we just have to wait for 8.2.1 (assuming your PR gets merged)

I don't think so, I had a quick look and I don't see a workaround. Until 8.2.1 I suggest people use the patched DLL I attached

**Comment by mcl-sz** [comment] 2019-10-21 11:32
When I add a "Embed"-grideditor (a Youtube video for example) the property the property data is show instead of the video html. Is this related to the bug with the RTE editor?

When I use the DLL that Jeavon provides, i still having the problem with rendering embeds

**Comment by skttl** [comment] 2019-10-21 11:54
Hi @mcl-sz, are you using the default Embed grid editor in Umbraco? That does not have anything to do with DTGE. Or are you embedding a macro in an RTE inside a DTGE?

**Comment by mcl-sz** [comment] 2019-10-21 12:16
Hi @skttl! No, when DTGE is installed, the Embed-editor (the grid control, not RTE) that's shiped with Umbraco doesn't work anymore.  

This is the model without DTGE installed:
![afbeelding](https://user-images.githubusercontent.com/18614643/67204049-eaf1a280-f40c-11e9-9edf-48a0d10d702e.png)

And this with DTGE installed:
![afbeelding](https://user-images.githubusercontent.com/18614643/67204173-36a44c00-f40d-11e9-96f6-c60bef2233d2.png)

The Value property disapears after installing DTGE

**Comment by FransdeJong** [comment] 2019-11-22 09:42
I encounter the same issue on v8.3 now. I've updated from 8.1.x to 8.3. All my RTE's break in doctype grid editor. Can someone point me in the right direction for a fix?

**Comment by mcl-sz** [comment] 2019-11-22 09:53
Hi Frans,

The cause indeed turned out not to be at all in DTGE but in the Grid partial "Embed" that is included with Umbraco. The structure of the Embed has changed but the partial supplied by Umbraco has not been updated for this.

Just try to add a Embed in a fresh Umbraco installation without having  DTGE installed, then the same error will occur. We created a new Grid partial view for Embed elements meeting our own requirements.

**Comment by FransdeJong** [comment] 2019-11-22 09:56
Just to be clear... I only have a string and RTE in the doctype. Or does DTGE use Embed to render the doctypes?

**Comment by skttl** [comment] 2019-11-22 11:31
DTGE does not use the Embed partial, but it's own.

Looking at the history, it seems to be merged 22/10 which was before 8.3 https://github.com/umbraco/Umbraco-CMS/commits/v8/dev/src/Umbraco.Web/PropertyEditors/RichTextPropertyEditor.cs

**Comment by skttl** [comment] 2019-11-22 11:38
@FransdeJong are you sure your update went well?

I just tried on 8.3 and it works here.

**Comment by FransdeJong** [comment] 2019-11-22 11:42
It's a cloud project so I assume it went well.... But yeah... Assumtion is...
I'll investigate further.

Thanks for looking in to this

**Closed** 2019-11-22 11:41 UTC
Labels: umbraco

**Comment by skttl** [comment] 2019-11-22 11:45
Mine was too, but only tried locally :)

Let me know if you find anything!

**Comment by FransdeJong** [comment] 2019-11-26 15:29
Umbraco Cloud forgot to update Umbraco.Web... Now all is fine
