### ISSUE TITLE
Cancelling adding a new editor in grid removes first item in cell instead of new editor

### ISSUE THREAD

**Issue by lars-erik** [skttl/umbraco-doc-type-grid-editor#185] opened 2020-04-14 18:40 UTC
Just trying out the 1.2 version.
When regretting adding a new item of the doctype editor type, hitting close removes the first item in the grid instead of the last one.
Can dig further, but it seems quite reproducable.
Hit me on slack or twitter if you need more info.

**Comment by skttl** [comment] 2020-04-14 18:57
Just tried, and can reproduce. I think this actually is a bug in Core, as the index of the newly created control is set wrongly to 1. That makes it remove the wrong one, because it removes by index.

I tried adding a core Embed control, and that one doesn't remove itself on closing, neither does the macro editor.

So maybe we should just don't remove the control on closing?

**Comment by skttl** [comment] 2020-04-14 19:01
Another solution could be to recalculate the index. 

The bug is here in umbraco.controllers.js
![image](https://user-images.githubusercontent.com/3726467/79263219-c265d500-7e92-11ea-911d-62491df8e1b1.png)

in $scope.addControl the index is always set to 1,

that index is used to remove the control by DTGE if empty, in $scope.removeControl

Here is the part of DTGE that removes the control: https://github.com/skttl/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Js/doctypegrideditor.controllers.js#L98

This could be extended to find the index of the current control in $scope.area.controls.

**Comment by skttl** [comment] 2020-04-14 19:02
/polls "Fix the existing implementation of removeControl" "Don't remove controls when closing"

**Comment by lars-erik** [comment] 2020-04-14 19:21
I think maybe just don't delete it. Think that's the general expectation on close.

**Comment by skttl** [comment] 2020-04-14 19:28
I think we need to delete empty empty controls - in other words multi doctype editors, where no doctype has been selected, because you can't render those.

I fixed it so it doesn't delete controls where a doctype has been selected, and also fixed a bug that probably has been in for a while. You probably don't wan't to click Close at all when using any of the DTGE versions right now. 🤔 https://github.com/skttl/umbraco-doc-type-grid-editor/commit/f594eb3ab108836147695e201ee6607a0ad4069c

You can try a build here, if you'd like:
https://ci.appveyor.com/project/skttl/umbraco-doc-type-grid-editor/builds/32178421/artifacts
or through MyGet
https://www.myget.org/feed/umbraco-packages/package/nuget/Our.Umbraco.DocTypeGridEditor/1.2.1-alpha-000055

I'll give it a few days for other problems to pop up, before releasing :)

**Closed by skttl** 2020-04-14 19:28 UTC

**Comment by lars-erik** [comment] 2020-04-14 20:34
Will try tomorrow! #h5yr  
Discovered it before learning I had to set element type.  
Could always just pop the area.controls array, but I guess there's a core BL method with a bug? 😕

**Comment by lars-erik** [comment] 2020-04-17 14:19
Fix seems to work, btw.
